apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/intel_numa0_res1
  name: east
  namespace: crucible-rickshaw
spec:
  config: '{ "cniVersion":"0.3.1","name":"east","type":"sriov","spoofchk":"on","trust":"on","ipam":{} }'


---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/intel_numa0_res2
  name: west
  namespace: crucible-rickshaw
spec:
  config: '{ "cniVersion":"0.3.1","name":"west","type":"sriov","spoofchk":"on","trust":"on","ipam":{} }'

