apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: configuration-nic
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration to set to 32 the nb of interrupt per NIC
      # override performance addons generated tuned profile
      include=openshift-node-performance-blueprint-profile
      [net]
      type=net
      devices_udev_regex=^INTERFACE=ens1f(0|1)
      channels=combined 32
    name: configuration-nic
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: "worker"
    profile: configuration-nic

